language: php
php:
  - 5.4
script: phpunit --configuration tests/phpunit.xml --coverage-text
notifications:
  irc: "irc.freenode.org#microsite"
services:
  - mongodb

env:
  - MONGO_VERSION=1.2.12

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
