language: php
php:
  - 5.4
script: phpunit --configuration tests/phpunit.xml --coverage-text
notifications:
  irc: "irc.freenode.org#microsite"
services:
  - mongodb
before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`