<?php
namespace Microsite;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-12 at 01:39:48.
 */
class AutoloaderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers Microsite\Autoloader::load
	 * @covers Microsite\Autoloader::register
	 * @covers Microsite\Autoloader::init
	 */
	public function testLoad()
	{
		Autoloader::init();
		Autoloader::register('Testing', BOOTSTRAP_DIR . '/data');
		$this->assertTrue(\Testing\TestClass::get_true());
	}
}
