<?php
namespace Microsite\DB\Mongo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-15 at 17:44:34.
 */
class MongoDBTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var DB $db
	 */
	protected $db;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->db = new DB('unittest');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		//$this->db->drop('test');
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::id
	 * @todo   Implement testId().
	 */
	public function testId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::isRef
	 * @todo   Implement testIsRef().
	 */
	public function testIsRef()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	public function testDatabaseCreation()
	{
		$this->db->insert('test', ['a' => 1, 'b' => 2]);
		$this->db->insert('test', ['a' => 3, 'b' => 4]);
		$cursor = $this->db->find('test', ['a' => 3]);
		$results = iterator_to_array($cursor);
		$result = reset($results);
		$this->assertEquals(4, $result['b']);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::find
	 * @todo   Implement testFind().
	 */
	public function testFind()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::finda
	 * @todo   Implement testFinda().
	 */
	public function testFinda()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::findField
	 * @todo   Implement testFindField().
	 */
	public function testFindField()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::findAssoc
	 * @todo   Implement testFindAssoc().
	 */
	public function testFindAssoc()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::findOne
	 * @todo   Implement testFindOne().
	 */
	public function testFindOne()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::count
	 * @todo   Implement testCount().
	 */
	public function testCount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::save
	 * @todo   Implement testSave().
	 */
	public function testSave()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::insert
	 * @todo   Implement testInsert().
	 */
	public function testInsert()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::lastError
	 * @todo   Implement testLastError().
	 */
	public function testLastError()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::updateConcurrent
	 * @todo   Implement testUpdateConcurrent().
	 */
	public function testUpdateConcurrent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::upsert
	 * @todo   Implement testUpsert().
	 */
	public function testUpsert()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::remove
	 * @todo   Implement testRemove().
	 */
	public function testRemove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::drop
	 * @todo   Implement testDrop().
	 */
	public function testDrop()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::batchInsert
	 * @todo   Implement testBatchInsert().
	 */
	public function testBatchInsert()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::group
	 * @todo   Implement testGroup().
	 */
	public function testGroup()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::ensureIndex
	 * @todo   Implement testEnsureIndex().
	 */
	public function testEnsureIndex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::ensureUniqueIndex
	 * @todo   Implement testEnsureUniqueIndex().
	 */
	public function testEnsureUniqueIndex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::getIndexInfo
	 * @todo   Implement testGetIndexInfo().
	 */
	public function testGetIndexInfo()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Microsite\DB\Mongo\DB::deleteIndexes
	 * @todo   Implement testDeleteIndexes().
	 */
	public function testDeleteIndexes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
