<?php
namespace Microsite;

use Microsite\DB\PDO\DB as DB;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-15 at 17:44:34.
 */
class MySQLDBTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var DB $db
	 */
	protected $db;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		if (extension_loaded('pdo')) {
			if(in_array('mysql', \PDO::getAvailableDrivers())) {
				$this->db = new DB('unittest');
			}
			else {
				$this->markTestSkipped(
					'The PDO mysql driver is not available.'
				);
			}
		}
		else {
			$this->markTestSkipped(
				'The PDO extension is not available.'
			);
		}
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		//$this->db->drop('test');
	}
}
