<?php
namespace Microsite;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-19 at 15:55:04.
 */
class TinycodeTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers Microsite\Tinycode::init
	 */
	public function testInit()
	{
		Tinycode::init(1, 8);
		$code1 = Tinycode::to_code(1);

		Tinycode::init(2, 8);
		$code2 = Tinycode::to_code(1);

		$this->assertNotEquals($code1, $code2);
	}

	/**
	 * @covers Microsite\Tinycode::to_code
	 * @covers Microsite\Tinycode::to_int
	 */
	public function testCoding()
	{
		Tinycode::init();

		for($orig = 1; $orig <= 300; $orig++) {
			$code = Tinycode::to_code($orig);
			$int = Tinycode::to_int($code);

			$this->assertEquals($orig, $int);
		}
	}

	/**
	 * @covers Microsite\Tinycode::max_int
	 */
	public function testMax_int()
	{
		Tinycode::init();
		$this->assertEquals(33232930569601, Tinycode::max_int());
	}
}
